/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bibliosystem.Ventanas;
import javax.swing.JOptionPane;
import com.mycompany.bibliosystem.Estudiante;
import com.mycompany.bibliosystem.Moderadores;

/**
 *
 * @author Pana_Waza
 */

public class tres extends javax.swing.JFrame {
    // esta variable ayuda a saber que estudiante ingreso (se comparte entre las demas ventanas)
    // se le pone protected para solo usar dentro de este paquete si da error ponerla publica 
    public static int carnetActual = 0;
    
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tres.class.getName());

    /**
     * Creates new form tres
     */
    public tres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quienIngresa = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Carnet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ad_user = new javax.swing.JRadioButton();
        mo_user = new javax.swing.JRadioButton();
        es_user = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Carnet");

        Carnet.addActionListener(this::CarnetActionPerformed);

        jLabel2.setText("Contraseña");

        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Regresar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Quien ingresa"));

        quienIngresa.add(ad_user);
        ad_user.setText("Administrador");
        ad_user.addActionListener(this::ad_userActionPerformed);

        quienIngresa.add(mo_user);
        mo_user.setText("Moderador");
        mo_user.addActionListener(this::mo_userActionPerformed);

        quienIngresa.add(es_user);
        es_user.setText("Estudiante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ad_user)
                    .addComponent(es_user)
                    .addComponent(mo_user))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ad_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mo_user)
                .addGap(18, 18, 18)
                .addComponent(es_user)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(Carnet)
                            .addComponent(jLabel1)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Carnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarnetActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int Ingreso=0;
        
        if(ad_user.isSelected()){
            Ingreso =1;
        }
        if (mo_user.isSelected()) {
            Ingreso = 2;
        }
        if (es_user.isSelected()) {
            Ingreso=3;
        }
        
    
        switch (Ingreso){
            case 3 ->{
                // Capturar los datos del usuario
            String carr = Carnet.getText();
            carnetActual = Integer.parseInt(carr);
            String contra = Password.getText();
        
            // verificar que el usuario exista 
            boolean existe = Estudiante.DatosRegistro("", carnetActual, contra, "",false);
            if ( existe == false) {
                JOptionPane.showMessageDialog(this,
                " Estudiante no encontrado ",
                " ERROR:",JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, 
                "Inicio de sesion exitoso",
                " Bienbenido:",
                JOptionPane.INFORMATION_MESSAGE);
            
                MenuUsuario ventanaUser = new MenuUsuario();
                this.dispose();
                ventanaUser.setLocationRelativeTo(null);
                ventanaUser.setVisible(true);
            }
                
            }
            case 2 ->{
                String carr = Carnet.getText();
                carnetActual = Integer.parseInt(carr);
                String contra = Password.getText();
                String name = Moderadores.getName(carnetActual,contra);
                
                if (!(name == "")) {
                    JOptionPane.showMessageDialog(this, "Bienbenido moderador","Entrada Exitoso",JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    MenuModerador ventana = new MenuModerador();
                    ventana.setLocationRelativeTo(null);
                    ventana.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, " Moderador no encontrado","Error : ",JOptionPane.ERROR_MESSAGE);
                    
                }
            }
            case 1 ->{
                if (Carnet.getText().equals("ADMIN") && Password.getText().equals("Admin")) {
                    JOptionPane.showMessageDialog(this, "Bienbenido Papi Disfruta otro dia  como admin 💪","Que honda rey",JOptionPane.YES_NO_OPTION);
                    this.dispose();
                    MenuAdmin ventana_ad = new MenuAdmin();
                    ventana_ad.setLocationRelativeTo(null);
                    ventana_ad.setVisible(true);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Quien jotas eres :<3 ???","Error : ",JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        uno ventana1 = new uno();
        ventana1.setLocationRelativeTo(null);
        this.dispose();
        ventana1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ad_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ad_userActionPerformed

    private void mo_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mo_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mo_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tres().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Carnet;
    private javax.swing.JTextField Password;
    private javax.swing.JRadioButton ad_user;
    private javax.swing.JRadioButton es_user;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mo_user;
    private javax.swing.ButtonGroup quienIngresa;
    // End of variables declaration//GEN-END:variables
}
